application: storm-tide
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /ingress/scripts
  static_dir: ingress/scripts
- url: /ingress/styles
  static_dir: ingress/styles
- url: /images
  static_dir: images
  mime_type: "image/gif"
- url: /.*
  script: index.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
